# Generated by Django 5.0.6 on 2024-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(default='https://spotlightonline.co/wp-content/uploads/2017/03/cinema_projector.jpg'),
        ),
    ]
