# Generated by Django 5.0.6 on 2024-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_small',
            field=models.URLField(default='https://spotlightonline.co/wp-content/uploads/2017/03/cinema_projector.jpg'),
        ),
    ]
