# Generated by Django 5.0.6 on 2024-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_movie_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='wished_by', to='base.movie'),
        ),
    ]
